### ISSUE TITLE
Pyflow RPM for Redhat/Centos

### ISSUE THREAD

**Issue by David-OConnor** [David-OConnor/pyflow#10]
If there's demand, I'll build them with each release.

**Comment by David-OConnor** [comment]
Related: Ubuntu snap release, for installing from its app store.

**Comment by David-OConnor** [comment]
RPMs will now be included with every release.

**Comment by David-OConnor** [comment]
Snaps will now be included with every release.

**Comment by batisteo** [comment]
I didn’t see in in the last release. Is it just an oversight?
