### ISSUE TITLE
Integration with Docker

### ISSUE THREAD

**Issue by theLastOfCats** [David-OConnor/pyflow#106]
Hi! 
Trying out your awesome project, but don't found how to use it with docker, especially with multistage builds.

Are there any examples?

**Comment by David-OConnor** [comment]
Sorry - I've never used docker. What would this look like? If you're using docker, couldn't you skip package management and do virtual system-wide deps?

**Comment by theLastOfCats** [comment]
@David-OConnor context is multistage Docker builds and minimizing dependencies (eg. compilers and libraries)
 
poetry does this via `RUN POETRY_VIRTUALENVS_CREATE=false poetry install` or by exporting requirements.txt and installing from it

**Comment by David-OConnor** [comment]
I'm leaning on this being out of scope. Sorry!
