### ISSUE TITLE
"pyflow install swifter" gives an error

### ISSUE THREAD

**Issue by tsuga** [David-OConnor/pyflow#118]
I'm using pyflow 0.3.0 on Windows 10 (64 bit).

When I tried to install [swifter](https://github.com/jmcarpenter2/swifter), I got an error.
Is there any way to fix this?

Regards,
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\me> cd .\.pyflow\envs\

PS C:\Users\me\.pyflow\envs> pyflow new test_project
Please enter the Python version for this project: (eg: 3.8)
Default [3.9.0]:3.9.0
Created a new Python project named test_project

PS C:\Users\me\.pyflow\envs> cd .\test_project\

PS C:\Users\me\.pyflow\envs\test_project> pyflow --version
pyflow 0.3.0

PS C:\Users\me\.pyflow\envs\test_project> pyflow install swifter
Installing swifter 1.0.7 ...
thread 'main' panicked at 'running setup.py bdist_wheel in folder "__pypackages__\\3.9\\lib\\swifter-1.0.7". Py path: "__pypackages__\\3.9\\.venv/Scripts\\python": Traceback (most recent call last):
  File "C:\Users\me\.pyflow\envs\test_project\__pypackages__\3.9\lib\swifter-1.0.7\setup.py", line 3, in <module>
    setup(
  File "C:\Users\me\.pyflow\envs\test_project\__pypackages__\3.9\.venv\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\me\AppData\Roaming\pyflow\python-3.9.0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\me\AppData\Roaming\pyflow\python-3.9.0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\me\AppData\Roaming\pyflow\python-3.9.0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\me\.pyflow\envs\test_project\__pypackages__\3.9\.venv\lib\site-packages\wheel\bdist_wheel.py", line 254, in run
    wf.write_files(archive_root)
  File "C:\Users\me\.pyflow\envs\test_project\__pypackages__\3.9\.venv\lib\site-packages\wheel\wheelfile.py", line 124, in write_files
    self.write(path, arcname)
  File "C:\Users\me\.pyflow\envs\test_project\__pypackages__\3.9\.venv\lib\site-packages\wheel\wheelfile.py", line 135, in write
    zinfo = ZipInfo(arcname or filename, date_time=get_zipinfo_datetime(st.st_mtime))
  File "C:\Users\me\AppData\Roaming\pyflow\python-3.9.0\lib\zipfile.py", line 361, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
', src\install.rs:363:21
stack backtrace:
   0:     0x7ff654e2911f - <unknown>
   1:     0x7ff654e4640a - <unknown>
   2:     0x7ff654e21038 - <unknown>
   3:     0x7ff654e2bcf6 - <unknown>
   4:     0x7ff654e2b7d9 - <unknown>
   5:     0x7ff654e2c336 - <unknown>
   6:     0x7ff654e2bf41 - <unknown>
   7:     0x7ff654e29a6f - <unknown>
   8:     0x7ff654e2be99 - <unknown>
   9:     0x7ff654e7f1dc - <unknown>
  10:     0x7ff654a80e06 - <unknown>
  11:     0x7ff654ae4e81 - <unknown>
  12:     0x7ff654ab9a4e - <unknown>
  13:     0x7ff654ac3ce2 - <unknown>
  14:     0x7ff654aef5c6 - <unknown>
  15:     0x7ff654aefb4c - <unknown>
  16:     0x7ff654e2c72a - <unknown>
  17:     0x7ff654ad32f7 - <unknown>
  18:     0x7ff654e6b0a4 - <unknown>
  19:     0x7ffbd6797c24 - BaseThreadInitThunk
  20:     0x7ffbd818d721 - RtlUserThreadStart
```

**Comment by tsuga** [comment]
I looked into this further and came up with some ideas for the fix. I appreciate your comments.

# (Possible) root causes
After some research, this error happens when creating a wheel file from a source, under a condition that the .tar.gz source file does not have `mtime` properties for the tar members.
![image](https://user-images.githubusercontent.com/2888173/120249975-8ddff300-c2b7-11eb-9e8a-377bbd22818d.png)

I looked at some other packages and turned out it is at random. Some packages like [pyrsistent](https://pypi.org/project/pyrsistent/#files) and [fiona](https://pypi.org/project/Fiona/#files) have `mtime` but others like [pandocfilters](https://pypi.org/project/pandocfilters/#files) don't.

The missing `mtime` causes an error for `pyflow` but not for `pip`. This difference comes from tar-unpacking implementations between `pip`  and Rust's `tar::Archive`.

## pip
`pip` reads tar members and save to a file using `shutil.copyfileobj(fp, destfp)` at [unpacking.py#L227](https://github.com/pypa/pip/blob/5554432d942f70b07ea755b2dab086374e3dfdf0/src/pip/_internal/utils/unpacking.py#L227)
So, no matter whether the `mtime` properties is set or not, `shutil.copy` sets a new timestamp for the file saved.

## pyflow (Rust `tar::Archive`)
`tar::Archive` just extract files as they are in the tar file. So it leaves the empty `mtime` as empty, and leads to the error.
There is a option `[set_preserve_mtime](https://docs.rs/tar/0.4.35/tar/struct.Archive.html#method.set_preserve_mtime)` available, but it won't fix the problem because the tar archive itself does not have `mtime` information of the member files.

# Solutions
There are two ideas for the fix. I prefer to fix pyflow, but do you have any preference on this?
## Fix pyflow
Add some codes to the end of [util.rs#L454](https://github.com/David-OConnor/pyflow/blob/9d08d8de7ac3fc01140fca6134adb77e6ffae21f/src/util.rs#L454
) to set `mtime` properties of member files to the current timestamp (same behaviour with `pip`) or the `mtime` property of the tar itself, if they are missing.
![image](https://user-images.githubusercontent.com/2888173/120251685-49efec80-c2bd-11eb-9afb-e068b972e772.png)


## Fix wheel (used to create a wheel, called by pyflow)
I managed to install the problematic packages by modifying 
[wheelfile.py#L130](https://github.com/pypa/wheel/blob/0b29b695ae458450217552978ad3094ed06a16d7/src/wheel/wheelfile.py#L130)
This workaround could be a permanent solution.
```python
def write(self, filename, arcname=None, compress_type=None):
	with open(filename, 'rb') as f:
		st = os.fstat(f.fileno())
		data = f.read()

	# zinfo = ZipInfo(arcname or filename, date_time=get_zipinfo_datetime(st.st_mtime))
	zinfo = ZipInfo(arcname or filename, date_time=get_zipinfo_datetime(st.st_mtime if st.st_mtime > 1.0 else st.st_ctime))
	zinfo.external_attr = (stat.S_IMODE(st.st_mode) | stat.S_IFMT(st.st_mode)) << 16
	zinfo.compress_type = compress_type or self.compression
	self.writestr(zinfo, data, compress_type)
```

**Comment by David-OConnor** [comment]
I think either of those fixes work. Fixing `wheel` is a more direct response to this, but if we can patch around it here, I'll merge it. My thoughts: Wherever it's easier to patch.
