### ISSUE TITLE
Add scoop install option for Windows

### ISSUE THREAD

**Issue by ciarancourtney** [David-OConnor/pyflow#12]
Involves contributing a JSON file to scoop repo describing where to get release binary by version etc

[pypy example](https://github.com/ScoopInstaller/Main/blob/master/bucket/pypy3.json)

**Comment by David-OConnor** [comment]
I'll add it.

**Comment by David-OConnor** [comment]
Config file added in latest commit. Will submit to Scoop after the next release.

**Comment by David-OConnor** [comment]
On Scoop; instructions updated.
