### ISSUE TITLE
Create a `brew` formula

### ISSUE THREAD

**Issue by oreksu** [David-OConnor/pyflow#121]
It would be great to add `brew` formula for Mac users.

**Comment by David-OConnor** [comment]
Would this allow me or someone else to build for Mac without owning one? This is why the Mac binaries are generally out of date.

**Comment by oreksu** [comment]
Sadly no. `brew` is simply a [package manager](https://brew.sh/) that lets you distribute binaries easily.
I am not sure if it is possible to make brew formula that compiles from source, but I can check if that would be interesting to you.

**Comment by David-OConnor** [comment]
Thanks for the follow up. Native mac binaries and Brew would be great, but I think as it stands, the best bet for Mac users is to install Rust, then `cargo install pyflow`.

**Comment by branchvincent** [comment]
hey @David-OConnor! I hit a small snag trying to create a `brew` formula. The [latest tagged release](https://github.com/David-OConnor/pyflow/releases/tag/0.3.0) doesn't include a necessary fix to compile on MacOS: https://github.com/David-OConnor/pyflow/commit/a2bf3ce7b066c747698b77403605d88545f8410e. Brew understandably disallows new formula that require a patch to build and has [asked](https://github.com/Homebrew/homebrew-core/pull/79682#issuecomment-864609110) if we can either:
* Tag a new (unplanned) release with this fix
* Get an idea for when the next release is planned

**Comment by branchvincent** [comment]
> Would this allow me or someone else to build for Mac without owning one? This is why the Mac binaries are generally out of date.

And to answer this, creating a Homebrew formula indeed means that Homebrew's CI will build/distribute binaries for Intel machines on MacOS 10.14/10.15/11 as well as ARM machines on MacOS 11!

And when `pyflow` has a new release, updating Homebrew's version involves creating a PR that is usually as simple as `brew bump-formula-pr pyflow --version=x.y.z` (unless any build-related changes occurred). If desired, you could of course integrate this as part of your release process (for example, see [GitHub's CLI](https://github.com/cli/cli/blob/936d6e1a8f0816b5076acc8172e73253b4b6a645/.github/workflows/releases.yml#L169-L175) and [starship](https://github.com/starship/starship/blob/09b12a52dd915d1391e593589f10f718a12e0f8d/.github/workflows/deploy.yml#L170-L178)).

**Comment by David-OConnor** [comment]
[Released as 0.3.0.1](https://github.com/David-OConnor/pyflow/releases)

Let me know if the 4-part non-semvar release name causes trouble.

Glad to hear about the easy Mac releases!

**Comment by branchvincent** [comment]
Thanks for the quick release, you can now `brew install pyflow`!

**Comment by David-OConnor** [comment]
Awesome
