### ISSUE TITLE
Option to specify Python version directly within single-file scripts

### ISSUE THREAD

**Issue by 00dani** [David-OConnor/pyflow#130]
Currently if I run `pyflow script some-script` and Pyflow hasn't seen that script before, it will prompt me interactively for a Python version to use. While Pyflow does remember my choice and will work fine for subsequent executions, it'd be preferable if the script itself could specify its desired Python version, allowing for completely hands-off execution of single-file scripts.

Either a variable like `__requires__`, or a command-line argument to `pyflow script`, should be made available that skips the interactive prompt and selects a specified Python immediately. (Perhaps both, allowing the command-line argument to override the variable?) With such support, Python scripts on path could be written like
```python
#!/usr/bin/env pyflow script --python=3.8
print("this is using python 3.8!")
```
Or perhaps like
```python
#!/usr/bin/env pyflow script
__python__ = "3.8"
print("this is using python 3.8!")
```
And would then run pretty much anywhere, without any special effort on the user's part beyond Pyflow being available.

**Comment by David-OConnor** [comment]
I agree that this would be a good addition.

**Comment by matteosantama** [comment]
Interesting idea. How should it behave when multiple Python versions are detected? This requires a secondary user-action.

```
pyflow script script.py
Please enter the Python version for this project: (eg: 3.8)
Default [3.8.9]:3.8.9
Found multiple compatible Python versions. Please enter the number associated with the one you'd like to use:
1: python3.8: 3.8.9
2: python3: 3.8.9
3: python: 3.8.9
```

**Comment by 00dani** [comment]
Hmm. All three of those Pythons in your example are exactly the same Python, 3.8.9, so just automatically picking (say) the top one should be okay, right?

I can see possible issues if there happen to be multiple Pythons 3.8 that are actually *different* versions of Python, though. Say, if you had this rather messed up situation:
```
$ pyflow script script.py
Please enter the Python version for this project: (eg: 3.8)
Default [3.8.9]:3.8
Found multiple compatible Python versions. Please enter the number associated with the one you'd like to use:
1: python3.8: 3.8.11
2: python3: 3.8.9
3: python: 3.8.10
```
But I think that's actually pretty easy to work around, just by requiring the value of `__python__` or `--python=` to be a *specific* Python version rather than a general one. If you have to type `__python__ = '3.8.11'` in your script, then Pyflow won't have any trouble deciding which Python you need.

Alternatively, just assuming you want the *newest* Python that matches your requested version would work. It's probably more reliable in terms of stable script behaviour to insist that you pin your script to an exact version though.

**Comment by David-OConnor** [comment]
Fixed in matteosantama's PR
