### ISSUE TITLE
Rust version of "editable install"

### ISSUE THREAD

**Issue by matteosantama** [David-OConnor/pyflow#132]
Hi there,

I am a long-time Python developer who has recently taken an interest in Rust. This project caught my eye as a way for me to sharpen my Rust skills, and I'm hoping to put together a few PRs. 

In Python, when developing a package, there is the concept of an "editable install" that lets you use the package in its current state. Is there a similar thing in Rust? In other words, if I intend to be actively developing my local version of `pyflow`, what is the best way for me to install it?

I saw `cargo install --path PATH` as an option, would you recommend that? The `CONTRIBUTING.md` doesn't offer much here.

**Comment by tanj** [comment]
I use `cargo install --path ./` to install a locally built release version. If I'm working with a debug release I'll use the direct path to the executable. `PROJECT_DIR/target/debug/pyflow`
