### ISSUE TITLE
Suggestion: Clippy

### ISSUE THREAD

**Issue by alok** [David-OConnor/pyflow#14]
I tried running `cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::cargo` over pyflow, and I noticed that it suggested fixes for some of your todos (especially with `filter_map`). You may find it handy.

**Comment by David-OConnor** [comment]
Sounds good; will give it a shot. There are also some issues that show up on Clippy with default settings, like excessive amounts of args, and complicated fns.

**Comment by alok** [comment]
You can disable specific warnings with `#![(...)]`

**Comment by David-OConnor** [comment]
All warnings from Clippy now pass except for fn complexity and too many args. Added that clippy line to the release checklist.
