### ISSUE TITLE
rpm link broken

### ISSUE THREAD

**Issue by wimglenn** [David-OConnor/pyflow#142]
It says:

> Fedora, CentOs, RedHat, or older versions of SUSE - Download and run this rpm.

But the release asset is not there https://github.com/David-OConnor/pyflow/releases/tag/0.3.1
 (404 at https://github.com/David-OConnor/pyflow/releases/download/0.3.1/pyflow-0.3.1.x86_64.rpm)
 
 When attempting to use the built executable instead (RHEL 7.7), I get the same error as in #50

```
$ pyflow --help
pyflow: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by pyflow)
```

**Comment by David-OConnor** [comment]
Hi - sorry about that. I've been unable to get it to compile on RedHat lately, due to CLI errors. I think the RH version is several Pyflow versions out of date. :( If you're able to build, I'm happy to host them.

**Comment by wimglenn** [comment]
I was able to build from source on RHEL to the point where `pyflow --version` works, but my build seems broken and I can't find any verbosity flags to get more output here.. I repeatedly get this error about "Problem getting dependency data"

```
pyflow install structlog
Found multiple compatible Python versions. Please enter the number associated with the one you'd like to use:
1: python3.6: 3.6.8
2: python3: 3.6.8
3: python: 3.6.8
1
🐍 Setting up Python...
Aborting graph creation: Problem getting dependency data
 Reqs: [
    Req {
        name: "structlog",
        constraints: [
            Constraint {
                type_: Caret,
                version: 21.1.0,
            },
        ],
        extra: None,
        sys_platform: None,
        python_version: None,
        install_with_extras: None,
        path: None,
        git: None,
    },
]
             It's taking a long time to get dependency data - this usually suggests that the dependency tree is being newly built. Please try again in a few minutes, and if the error still occurs, consider opening an issue on github.
```

**Comment by wimglenn** [comment]
Guess this project is dead
