### ISSUE TITLE
Any interest in supporting PEP 665?

### ISSUE THREAD

**Issue by brettcannon** [David-OConnor/pyflow#153]
I'm talking to various packaging projects and asking if they would be willing to publicly state support for [PEP 665](https://www.python.org/dev/peps/pep-0665/). If you would, could you either let me know directly or leave a comment at https://discuss.python.org/t/pep-665-take-2-a-file-format-to-list-python-dependencies-for-reproducibility-of-an-application/11736 ?

Thanks!

**Comment by David-OConnor** [comment]
This looks like a nice way to deal with dependency specifications. Given how popular dependencies are on Python projects, included nested ones, I like the idea.

**Comment by brettcannon** [comment]
Thanks! I mention you like the idea in a future PEP update.
