### ISSUE TITLE
Python versioning questions

### ISSUE THREAD

**Issue by NoelTautges** [David-OConnor/pyflow#154]
Hi, Pyflow looks really interesting! I have a couple questions about how it chooses and downloads Python versions.

Currently, the Python version resolver [chooses a fixed patch based on the Python version](https://github.com/David-OConnor/pyflow/blob/872d042c3aa1a5f2774756df3368f1a2247cc5d1/src/py_versions.rs#L44) and [downloads it from the releases of your other repo](https://github.com/David-OConnor/pyflow/blob/872d042c3aa1a5f2774756df3368f1a2247cc5d1/src/py_versions.rs#L241) [`pybin`](https://github.com/David-OConnor/pybin/releases). It [stores the user-provided Python version in `pyproject.toml` under `tool.pyflow.py_version`](https://github.com/David-OConnor/pyflow/blob/872d042c3aa1a5f2774756df3368f1a2247cc5d1/src/files.rs#L358).

1.) The list of versions in `pybin` [seems to be updated manually](https://github.com/David-OConnor/pyflow#repo-binaries-are-downloaded-from). Given that it's probably a lot of time to do it by hand, would there be any interest in a pull request to update the list with new versions upon release with a GitHub Actions job or such?

2.) `py_version` is a raw version number and doesn't include constraints like `^` that allow for patch upgrades in the same minor release. Would there be any interest in a pull request to add them to the field?

Thank you for your time! I'm considering using Pyflow for new projects and I'd love to see it grow.

**Comment by David-OConnor** [comment]
1 - yep! I agree the updating manually is tedious. Eg building each version for different OSes and Linux flavors etc.
2 - Yep!

If you address these with PRs, I will merge them.

**Comment by NoelTautges** [comment]
Thanks!
