### ISSUE TITLE
Configuring PyCharm for use with __pypackages__

### ISSUE THREAD

**Issue by dmontagu** [David-OConnor/pyflow#21]
I noticed this comment at the bottom of the docs:

> You may need to set up IDEs to find packages in `__pypackages__`. If using PyCharm, using the tree on the left, right click `__pypackages__/3.x/lib`, select Mark directory as, Sources Root.

I haven't used the tool yet, but I'm assuming that `__pypackages__` plays a similar role to the `site-packages` directory in a typical virtual environment.

If that's the case, *rather* than marking the directory as a sources root, I think you'd want to mark it as one of the "Interpreter Paths". Otherwise you'll get atypical search result behavior -- searching in your "Project" will also turn up results in the dependency packages.

(You could still search in the `__pypackages__` folder under this approach by selecting it in the "Project" tab before triggering the "Find in Path" action, but if you mark it as a Sources Root I don't think there is an easy way to *only* search in your *actual* project.)

-------

To mark a folder as one of the "Interpreter Paths" in PyCharm, you do:

Settings -> Project -> Project Interpreter -> (Settings Cog) -> Show All... -> Select the interpreter -> Click the folder-tree icon at the bottom of the pop-out window -> Click the + icon at the bottom of the new pop-out window -> Navigate to and select the folder you want to add (i.e., `__pypackages__`)

Admittedly this is relatively painful, but I think it would give a more typical PyCharm experience with a project structured like this.

(I haven't done it though so I could be wrong! Just figured it might be worth updating the docs if this is right and/or you've noticed any issues with the "Mark as Sources Root" approach.)

**Comment by David-OConnor** [comment]
Spot on - I hadn't run across issues with `Sources Root`, but it didn't seem like an accurate description. `__pypackages__/3.x/lib` is indeed equivalent to `site-packages`. Your fix works on my end, although I agree it's a more involved than ideal. Updated the readme with your instructions.
