### ISSUE TITLE
Mac binary

### ISSUE THREAD

**Issue by David-OConnor** [David-OConnor/pyflow#3]
There are currently no Mac binaries or installers available. There should be no reason this doesn't work on Mac, but it's untested, and requires building from source, or installing via `Cargo` for now.

**Comment by mikaelho** [comment]
There is a request for a PR for the Mac binary in the docs. I just installed pyflow via cargo. How should I contribute the binary, if it is still needed?

**Comment by David-OConnor** [comment]
That would be much appreciated. I don't think there's a way to directly PR a release, but if you clone the repo, build, add the release binary to the main folder and submit a PR, I'll be able to add that binary to the releases page.

Steps:
- Clone and navigate into the repo path
- rustup update
- rustup build --release
- There should be a binary in `pyflow/target/release`; move that to the main `pyflow` folder
- Submit a PR

I just pushed/released v0.1.7, so this binary will be in sync with the existing ones.

I have no experience with Mac - is the binary Rust produces in a format that's easy to install/use on Mac? Would it be easier to use if packaged for HomeBrew? Using `cargo install` isn't ideal if the user doesn't already have Rust installed, since it's a big download, takes a while, and has multiple steps; I'd like to make this as easy as possible.

**Comment by russelldavis** [comment]
I followed the steps above (note the third bullet point should call `cargo` not `rustup`) with the repo checked out at the 0.2.4 tag. The resulting binary (zipped) is [attached here](https://github.com/David-OConnor/pyflow/files/4286023/pyflow.zip). (I figured that'd be simpler than a PR, since you ultimately only want to upload it to the release page, right?)

> is it a standalone file that can be run with ./pyflow as you would in Linux?

Yep

> Would it be easier to use if packaged for HomeBrew?

I do think a homebrew package would be what most mac developers would prefer/expect.

> Using cargo install isn't ideal 

+1

**Comment by David-OConnor** [comment]
Awesome! Added to the release, and updated the Readme instructions.

**Comment by yig** [comment]
The link on the main README is broken.

**Comment by David-OConnor** [comment]
Fixed. Note that this binary is one version behind.

**Comment by cynipe** [comment]
I noticed that there is no mac binary after 0.2.4.
Has official support been discontinued?

found: https://github.com/David-OConnor/pyflow/releases/download/0.2.4/pyflow_mac_0.2.4.zip
not found: https://github.com/David-OConnor/pyflow/releases/download/0.2.5/pyflow_mac_0.2.5.zip

**Comment by David-OConnor** [comment]
@ryuta69 just uploaded one.

https://github.com/David-OConnor/pyflow/releases/download/0.2.8/pyflow_mac_0.2.8.zip

**Comment by David-OConnor** [comment]
Now avail with Brew.
