### ISSUE TITLE
Cannot install packages

### ISSUE THREAD

**Issue by madig** [David-OConnor/pyflow#30]
Pyflow 0.1.9, Fedora 31, Python 3.7.5.

```
/tmp $ pyflow new ppp
Created a new Python project named ppp

/tmp $ cd ppp

/t/ppp (master|…) $ nvim pyproject.toml

/t/ppp (master|…) $ cat pyproject.toml 
# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = ""
py_version = "3.7"
version = "0.1.0"
authors = ["..."]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
pytest = "*"

/t/ppp (master|…) $ pyflow install
Found multiple compatible Python versions. Please enter the number associated with the one you'd like to use:
1: python3.7: 3.7.5
2: python3: 3.7.5
3: python: 3.7.5
3
🐍 Setting up Python...
🔍 Resolving dependencies...
Problem getting dependency data - this is likely a bug in the cacheing process. Please try again in a few minutes. Reqs: [
    Req {
        name: "six",
        constraints: [],
        extra: None,
        sys_platform: None,
        python_version: None,
        install_with_extras: None,
        path: None,
        git: None,
    },
    Req {
        name: "pyparsing",
        constraints: [
            Constraint {
                type_: Gte,
                version: 2.0.2,
            },
        ],
        extra: None,
        sys_platform: None,
        python_version: None,
        install_with_extras: None,
        path: None,
        git: None,
    },
]
```

**Comment by David-OConnor** [comment]
This is caused by `*` dependencies not being supported. It'll work if you use `pyflow add pytest --dev`, or replace the relevant line with `pytest = "^5.2.2"`.

**Comment by madig** [comment]
Hm. I tried `^5`, too, and that didn't work either. Do I need a minor version?

**Comment by David-OConnor** [comment]
I think I'm wrong. It does seem to be working with a `*` import now. I think this is a bug on the dependency-cache side. Should be fixed now, and work by adding via CLI, using your original file, or using just `^5`.

**Comment by madig** [comment]
With git master (`1961fc74d278022d155ad199b2af998161fe0ae0`), `^5` and `*` indeed work. Thanks!

**Comment by David-OConnor** [comment]
I think this is the same problem [as this](https://github.com/David-OConnor/pyflow/issues/16). Ie, `pyparsing` doesn't have dependencies listed on `pypi`, so we have to check by downloading the package, running setup.py, and checking deps manually, which is where the timeout is occuring. Once complete for a given package//version combo, this won't come up again. (Why it seems solved on your end), but this could still come up for other packages or new versions of `pyparsing`.
