### ISSUE TITLE
[UI] Unneccesary question about multiple system Python

### ISSUE THREAD

**Issue by batisteo** [David-OConnor/pyflow#33]
I’m using Fedora and after creating a new project, I was asked the following:
```bash
$ pyflow install aiohttp
Found multiple compatible Python versions. Please enter the number associated with the
  one you’d like to use:
1: python3.7: 3.7.5
2: python3: 3.7.5
3: python: 3.7.5
```

Pyflow could detect it’s linking to the same version. Maybe it could even see if it’s about symlink to the same binary.  
And then not ask this question.

**Comment by David-OConnor** [comment]
Agreed - that behavior would be better.

**Comment by David-OConnor** [comment]
Behavior has recently improved here.
