### ISSUE TITLE
Error parsing Os

### ISSUE THREAD

**Issue by nuno-andre** [David-OConnor/pyflow#34]
```
[tool.pyflow.dependencies]
pywebview = { git = "https://github.com/r0x0r/pywebview" }
```
[causes](https://github.com/David-OConnor/pyflow/blob/master/src/util.rs#L57)
```
❯ pyflow install
thread 'main' panicked at 'Problem parsing Os in extras: openbsd6', src\dep_types.rs:706:49
```
[because of](https://github.com/r0x0r/pywebview/blob/master/setup.py#L14)
```
install_requires = [
    ...,
    'PyQt5 ; sys_platform == "openbsd6"',
]
```

The point is that I'm running pyflow in Windows.

Given that `sys.platform` is built dynamically [in most POSIX systems](https://docs.python.org/3/library/sys.html#sys.platform), as are other PEP508's environment markers, I think that a best-effort parsing of `install_requires` would be a more resilient approach.

Thank you for your work :) Python is greatly in need of tools like this.

**Comment by David-OConnor** [comment]
Fixed in latest commit. The solution of treating it as Linux is a kludge, since we don't have BSD support - I'm not sure which platform-specific routes would compile to it, but it should now handle this and move on instead of crashing when it sees BSD specified.

**Comment by David-OConnor** [comment]
It looks like neither PEP 508 nor [the sys module docs](https://docs.python.org/3.8/library/sys.html)  have a comprehensive list. [this SO post](https://stackoverflow.com/questions/446209/possible-values-from-sys-platform) is the best I can find. Also using some tricks like if the name contains `bsd`, `linux` etc. Let me know if you have a more comprehensive/official list.

**Comment by nuno-andre** [comment]
The point is that [these requirements are abstract](https://packaging.python.org/discussions/install-requires-vs-requirements/), and were devised to be interpreted by the application according its context. So there will be nothing like an exhaustive list of values for those requirements.

And I think this is a great design because, to my mind, there's no reliable way to model such an ever changing domain.

I usually find them easier to handle by reversing the evaluation in a lazy and best-effort approach, rather than attempting to model every single dependency; since you know how to evaluate the markers of the systems you support, but not many others which actually do not matter. In this way, this issue is not a bug, but an enhancement ;)

The flow in naïve-Python would be roughly like:

```
requirements_that_matter = list()

for requirement in install_requires:
    for marker, value in requirement.markers.items():
        if value not in this_specific_system.get_values_for(marker):
            break
    requirements_that_matter.append(requirement)
```

I think this approach makes the dependency management easier, especially the transitive ones.

It's great to hear about your commit. I'm going to try the build again and I'll give you feedback. Thanks!

**Comment by David-OConnor** [comment]
Should be fixed
