### ISSUE TITLE
`pyflow switch` does nothing

### ISSUE THREAD

**Issue by madig** [David-OConnor/pyflow#39]
1. `git clone https://github.com/daltonmaag/statmake`
2. `pyflow install`
3. `pyflow` -- should display some 3.6.x version
4. `pyflow switch 3.8` -- or something else you have lying around
5. `pyflow` -- still displays 3.6.x :(

**Comment by David-OConnor** [comment]
Bug introduced in a recent version

**Comment by David-OConnor** [comment]
It looks like it might have been working as intended after all (It just switched the version in `pyproject.toml`.) In the latest commit, it now also updates the environment and syncs dependencies as required.

**Comment by David-OConnor** [comment]
Additionally, a recent version made almost all the commands sync/setup as required, ie so you can just run what you need without setup, assuming pyproject toml is correct. Eg just run `pyflow` naked.

**Comment by madig** [comment]
It installs deps for 3.8 now, but running `pyflow` still drops me into a 3.6 shell :o

**Comment by David-OConnor** [comment]
I'm able to repro; standby.

**Comment by David-OConnor** [comment]
This is caused by a bug in reconciling Poetry's `pyproject.toml` syntax for specifying python versions and Pyflow's.

**Comment by David-OConnor** [comment]
In the meanwhile, you can add this to `pyproject.toml`:
```toml
[tool.pyflow]
py_version = "3.8"
```

**Comment by madig** [comment]
Thanks, but no rush :) I'm just playing around when I have some time, I'm not expecting you to fix bugs on a weekend :smiley:

**Comment by David-OConnor** [comment]
Released.

**Comment by madig** [comment]
```
/t/statmake (master|✚1…) $ pyflow switch 3.8
Switched to Python version 3.8
🐍 Setting up Python...
⬇ Installing cattrs 0.9.0 ...
⬇ Installing fonttools 4.2.2 ...
Added a console script: fonttools
Added a console script: pyftmerge
Added a console script: pyftsubset
Added a console script: ttx
⬇ Installing appdirs 1.4.3 ...
⬇ Installing fs 2.4.11 ...
⬇ Installing pytz 2019.3.0 ...
⬇ Installing attrs 19.3.0 ...
⬇ Installing setuptools 42.0.2 ...
Added a console script: easy_install
Added a console script: easy_install-3.8
⬇ Installing six 1.10.0 ...

/t/statmake (master|✚1…) $ pyflow 
Python 3.6.9 (default, Sep 20 2019, 09:13:05)
[...]
```

:(

`switch` does not seem to alter pyprojects.toml.
