### ISSUE TITLE
Suggestion: Generates LICENSE with content or not create LICENSE

### ISSUE THREAD

**Issue by eduidl** [David-OConnor/pyflow#45]
Hello.

Now, `pyflow init` generates `LICENSE`, which I don't think is useful.
This is because I create license file on github.com, and empty `LICENSE` makes it unavailable.
I have two alternative ideas as follows.

1. `pyflow init` does not create `LICENSE`
2. `pyflow init` make user choose using license (including nothing),  and generates it as users choose.

As you know, `cargo new` does not create `LICENSE`, for the first idea is sufficient, I think.
Please think on it.

Regards.

**Comment by David-OConnor** [comment]
I'm leaning towards this being good

**Comment by David-OConnor** [comment]
Done; option 1.
