### ISSUE TITLE
Adherence to XDG User Directories or Systemd file-heirarchy spec

### ISSUE THREAD

**Issue by danielloader** [David-OConnor/pyflow#5]
Hey, thanks for making this tool - trying it out now.

Noticed installation of python binaries goes into ~/python-installs, I'm on a bit of a crusade to clean up my home directory so I know what's worth backing up and not. 

Would it be possible to put them in a ~/.local subdirectory? 
In this example I think the path would be ~/.local/bin/python-installs/

Got this by running `systemd-path user-binaries`.

Just wanted to open up a discussion on where installed resources land in a user directory! Feel free to mark this closed if ~/python-installs is by design or by preference.

Thanks again!

More here:
https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory

**Comment by David-OConnor** [comment]
`~/python-installs` was an arbitrary choice. I agree with your points, and will make a change to something more appropriate. I hear the `directories` crate may help address this in a cross-platform way.

**Comment by David-OConnor** [comment]
Fixed in latest commit. Uses `~/.local/share/pyflow` on Linux, `~\AppData\Roaming\pyflow` on Windows, and `~/Library/Application Support/pyflow` on Mac. Open to alternatives.

**Comment by David-OConnor** [comment]
Released in 0.1.1.

**Comment by David-OConnor** [comment]
I'm happy with the way this is now. Can open new issues with specific suggestions for how to structure and where to place these directories.
