### ISSUE TITLE
pyflow: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by pyflow)

### ISSUE THREAD

**Issue by pawamoy** [David-OConnor/pyflow#50]
Is version 2.18 mandatory, or could it work with 2.17?

**Comment by David-OConnor** [comment]
Not sure. Could you please post your `pyproject.toml` ?

**Comment by pawamoy** [comment]
OS is Red Hat Enterprise Linux 7. I checked online and the latest version of glibc shipped for RHEL7 is 2.17 (hence my question above). 

I don't even have a pyproject.toml file yet: simply running `pyflow` generates this message, with or without options (`-h`, `--help`, etc.).

I installed it with `pipx`, which should be equivalent to the `pip` installation method.

**Comment by David-OConnor** [comment]
I think I understand this better now. What happens if you install using the RPM? 

The reason the RPM exists is partly because RH/CentOs etc use older system libs than other OSes: They're deliberately built on CentOS 7.

**Comment by pawamoy** [comment]
Unfortunately the RPM download URL is not whitelisted by my corporate proxy, so I cannot try it 🙂 

I totally understand that using pip to install pyflow on Red Hat is not the recommended method, so you can safely close this issue since Red Hat is already mentioned in the readme, saying that the RPM package must be used.

I wonder if a conda package would help here.

Anyway, thank you for your help!

**Comment by David-OConnor** [comment]
Updated the readme to indicate the pip version is unlikely to work with RH family distros. It might be feasible to submit wheels built on CentOs (Which I suspect will work on your system) to Pypi in addition to ones built on a newer Linux OS, but I'm not sure how that would work, ie if pip would know which to use. Currently there's just one Linux and one Windows wheel.

**Comment by pawamoy** [comment]
Interesting! I have no experience with publishing wheels for different operating systems on PyPI, I will take a look into that :slightly_smiling_face:
