### ISSUE TITLE
Scoop install proceeds on 32bit windows

### ISSUE THREAD

**Issue by ciarancourtney** [David-OConnor/pyflow#56]
Since pyflow.exe is 64bit only (AFAIK?) it should probably only have a `architecture.64bit` key in the [scoop json manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/pyflow.json) as per the scoop [spec](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties).

Or leave everything as is and just build a 32bit version going forward, I doubt there are any perf benefits that justify the slightly larger binary size?

For reference pyflow.exe v0.2.5.1 returns exit code 216 on windows 7 32bit.

**Comment by David-OConnor** [comment]
Good catch. 64 bit's been standard for so long; don't need to build 32-bit binaries.

PR: https://github.com/ScoopInstaller/Main/pull/904/files

**Comment by David-OConnor** [comment]
merged

**Comment by ciarancourtney** [comment]
Confirmed

    scoop install pyflow
    'pyflow' doesn't support 32bit architecture!
