### ISSUE TITLE
Support for __main__.py

### ISSUE THREAD

**Issue by monospacedmagic** [David-OConnor/pyflow#59]
I plan to adopt pyflow early in a production environment despite how young it is simply because it's that good. However I can't seem to be able to even run my project. Here's my (simplified) project structure:

    __pypackages__
        [...]
    myproject
        __main__.py
    pyproject.toml

Here's what I've tried so far:

- `pyflow -m myproject`

> error: Found argument '-m' which wasn't expected, or isn't valid in this context

- `pyflow myproject`

> Problem running the CLI tool myproject. Is it installed?

- `pyflow python -m myproject`

> error: Found argument '-m' which wasn't expected, or isn't valid in this context

- `__pypackages__\3.7\.venv\Scripts\activate.bat` followed by `python -m myproject`

> ModuleNotFoundError: No module named 'click'

(__main__.py tries to import click but it fails.)

I'm out of ideas. Any help is appreciated!

Edit: I've now moved `__main__.py` out of `myproject` and renamed it to `run.py`, and I run it with `pyflow run.py`. It would be better if pyflow supported the [standardized](https://docs.python.org/3/library/__main__.html) `__main__.py` in some way, though.

**Comment by David-OConnor** [comment]
As you've discovered, this is due to limitations on Pyflow's CLI. I think it would be nice to support the flow you tried, since it's intuitive, and consistent with existing python syntax. I'll add it.

**Comment by monospacedmagic** [comment]
Possibly related: It seems that pyflow just tries to consume all flags, even those that were intended for the python script I'm trying to run.

```
myproject>pyflow run.py --test
error: Found argument '--test' which wasn't expected, or isn't valid in this context

USAGE:
    pyflow [script]... [SUBCOMMAND]

For more information try --help
```

**Comment by David-OConnor** [comment]
I can confirm this. There's something wonky with the arg parsing handling. I think I need to re-organize that section of the code; making the initial change should have been easy, but I ran into trouble. May switch off the `structopt` dependency, which manages this.
