### ISSUE TITLE
Support for development only packages?

### ISSUE THREAD

**Issue by danielloader** [David-OConnor/pyflow#6]
Can you install dependencies are dev only? Akin to `poetry add --dev flake8`?

**Comment by danielloader** [comment]
Noticed you can install extras with the `-e` flag, is this meant to be the equivalent?

**Comment by David-OConnor** [comment]
No - it's planned, but not implemented. Extras are different - they're dependencies that can be included optionally to enable features. Ie the `qtconsole` extra for `ipython` adds the `qtconsole` dependenc.

**Comment by David-OConnor** [comment]
In the latest release.

**Comment by espositofulvio** [comment]
I'm just trying pyflow so I might be missing something, but dev-dependencies doesn't work for me. They don't get installed. I'm using 0.1.3 on WSL Ubuntu. I tried specifying them directly in the pyproject.toml file, and also searched for a pyflow install --dev or something but couldn't make it work. Any advises?

**Comment by David-OConnor** [comment]
This is a bug. Fixed in latest commit. Added a `pyflow install black --dev` command that wasn't there before. Expect a new release soon.

**Comment by espositofulvio** [comment]
yep, thanks. You've been quick :)
