### ISSUE TITLE
Installing future fails

### ISSUE THREAD

**Issue by mboratko** [David-OConnor/pyflow#61]
Thanks for creating this! I ran into an issue, however, upon initial usage when using pyflow to install pytorch:

```
~> pyflow new test_pyflow_1
Please enter the Python version for this project: (eg: 3.8)
3.7
Created a new Python project named test_pyflow_1
 > cd test_pyflow_1/
 ~/test_pyflow_1 > ../pyflow install torch
🐍 Setting up Python...
⬇ Installing future 0.18.2 ...
thread 'main' panicked at 'Problem running setup.py bdist_wheel: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I am running on Arch Linux with kernel 5.6.7. I tried using the downloadable binary, installing via cargo, and using the package in the AUR, all with the same result.

**Comment by David-OConnor** [comment]
This is likely the same as https://github.com/David-OConnor/pyflow/issues/57 and https://github.com/David-OConnor/pyflow/issues/55. Ie, something is going wrong when building a wheel from a source-only distro. I haven't figured out what's going on, but its behavior appears to depend on the OS being used, and whether a system python, or one installed with pyflow is being used.

**Comment by David-OConnor** [comment]
Released 0.2.6, which should fix this.

**Comment by mboratko** [comment]
Thank you, I have finally gotten around to trying this again but was met with another error on 0.2.6:

```
I  ~ > pyflow new test_pyflow_5 
Please enter the Python version for this project: (eg: 3.8)
3.7
Created a new Python project named test_pyflow_5
 I  ~ > cd test_pyflow_5
 I  ~/test_pyflow_5 > pyflow install torch
🐍 Setting up Python...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', /home/mboratko/.cargo/registry/src/github.com-1ecc6299db9ec823/pyflow-0.2.6/src/util.rs:643:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I tried installing the newest version using `cargo install pyflow` but ran into a different issue on install:

```
error[E0308]: mismatched types
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pyflow-0.2.7/src/install.rs:405:29
    |
405 |                 util::abort(error);
    |                             ^^^^^
    |                             |
    |                             expected `&str`, found struct `std::string::String`
    |                             help: consider borrowing here: `&error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `pyflow v0.2.7`, intermediate artifacts can be found at `/tmp/cargo-installLacqvU`

Caused by:
  could not compile `pyflow`.
```

(The above happens when I specify --version=0.2.7 but a similar issue appears if I just install the latest as well.)

**Comment by David-OConnor** [comment]
Fixed in latest commit with a bandaid. I'd never seen that architecture flag before. (It's not really manylinux if it's for aarch?)  Overall, might need a better way to support these manylinux variants.

**Comment by mboratko** [comment]
Thank you very much, seems to be working now!
