### ISSUE TITLE
invalid gzip header error when installing `simplegeneric`

### ISSUE THREAD

**Issue by sbdchd** [David-OConnor/pyflow#64]
I was trying to install [`ipdb`](https://pypi.org/project/ipdb/), but its dependency [`simplegeneric`](https://pypi.org/project/simplegeneric/) failed to install with an `invalid gzip header` error

```shell
❯ cd "$(mktemp -d)" && pyflow init && RUST_BACKTRACE=1 pyflow install simplegeneric
Created `pyproject.toml`
🐍 Setting up Python...
Found lockfile
⬇ Installing simplegeneric 0.8.1 ...
Problem upacking: Custom { kind: InvalidInput, error: "invalid gzip header" }
```

pyflow 0.2.6
Python 3.7.3
OS: macOS 10.15.4

**Comment by David-OConnor** [comment]
Fixed in latest commit. I think this was introduced by an update in the `Tar` package, which now fails on zips while iterating over an archive's entries, vice opening the archive.

**Comment by lhaze** [comment]
>Might do a new release, because this potentially affects all packages that don't have wheels, and use zip files for their source.

Please, do. Many common packages have this type of build and this bug blocks using pyflow in environment containing them.

**Comment by David-OConnor** [comment]
Done: 0.2.7
