### ISSUE TITLE
Minor README error - PyCharm config 

### ISSUE THREAD

**Issue by LemuelCushing** [David-OConnor/pyflow#65]
There's a possible typo in [README.md Gotchas](https://github.com/David-OConnor/pyflow/blob/master/README.md#gotchas), I think.

The interpreter path is written as `(projname)/__pypackages__/3.x/.venv/bin/python`, shouldn't that be `/Scripts/python`? That seems to work, if I'm not missing anything.

(Although, pointing VSCode to that interpreter path doesn't help connecting to its debugger, which I don't quite understand)

**Comment by David-OConnor** [comment]
I think it's `Scripts` on Windows, and `bin` on Linux and mac. Updated the readme. I haven't used the VScode debugger. PRs welcome if you figure out a better way to configure it.
