### ISSUE TITLE
pyflow new should offer a default value for Python

### ISSUE THREAD

**Issue by ksamuel** [David-OConnor/pyflow#70]
If you do "pyflow new", you'll get prompted:

```
Please enter the Python version for this project: (eg: 3.8)
```

But if I type enter, it complains that I didn't enter a value. While I would expect it to actually take 3.8 as the default value if I don't type anything.

If you approve this change, I can make a PR.

**Comment by David-OConnor** [comment]
Sounds good! Will merge the PR
