### ISSUE TITLE
pyflow init and pyflow new should be consistent

### ISSUE THREAD

**Issue by ksamuel** [David-OConnor/pyflow#71]
`pyflow new` prompts me for the Python version, but not `pyflow init`. Both should have the same behavior.

**Comment by David-OConnor** [comment]
I've gone back and forth on this, but agree - that would be a good change. I think the solution is to have `pyflow init` ask explicitly, instead of choosing a default as it does currently.

**Comment by David-OConnor** [comment]
Added in latest commit.
