### ISSUE TITLE
After failing to build a wheel, installing anything becomes impossible

### ISSUE THREAD

**Issue by ksamuel** [David-OConnor/pyflow#72]
Doing this:

```
 pyflow install cheat
Found lockfile
Installing termcolor 1.1.0 ...
Installing cheat 2.5.1 ...
Problem building cheat from source. This may occur if a package that requires compiling has no wheels available for Windows, and the system is missing dependencies required to compile it, or if on WSL and installing to a mounted directory.
```

If you try to install any other packages, it tries to reinstall cheat and fail every time:

```
λ pyflow install tldr
Installing cheat 2.5.1 ...
Problem building cheat from source. This may occur if a package that requires compiling has no wheels available for Windows, and the system is missing dependencies required to compile it, or if on WSL and installing to a mounted directory.
```

**Comment by David-OConnor** [comment]
As a workaround, you can run `pyflow reset`, but yikes - I need to fix this.

**Comment by bowmanjd** [comment]
I am seeing the same thing. When I `pyflow install httpx`:

```bash
⬇ Installing idna 2.0.0 ...
Problem building idna from source. This may occur if a package that requires compiling has no wheels available for this OS and this system is missing dependencies required to compile it.Try running `pip install --upgrade wheel`, then try again
```

Any way we can help?

**Comment by mindriot101** [comment]
This seems to occur when the python installation does not have the wheel package installed. I got this working by installing wheel.

**Comment by bowmanjd** [comment]
Fascinating. If I first `pyflow install wheel` everything works fine after that.

**Comment by David-OConnor** [comment]
Excellent find. What OS are y'all experiencing this error on? Are you using system Python, or one installed by pyflow?

**Comment by mindriot101** [comment]
I tried on both macOS and linux (arch) using python previously installed via asdf.

I cannot replicate @bowmanjd 's advice as trying to install `wheel` with pyflow fails (as `wheel` is not installed 🤦 ) but installing it to the python installation first solves the problem. In fact it is the advice given in the error message for linux and macos.

It may be useful to capture the `stderr` of the `std::process::Command` that is running `python setup.py bdist_wheel` output and display it if the process exit status is not 0, or at least use the `stderr` to internally resolve the problem. In fact the `std::process::Command` status codes are not checked. They probably should be.

**Comment by bowmanjd** [comment]
That is an excellent question. I am using Fedora 32 and its system Python (3.8.5).

If I use Python 3.7 (in other words, one that Pyflow installs) I do not see this problem.

**Comment by bowmanjd** [comment]
So, if I first `sudo python -m pip install wheel` (that's with my system Python 3.8.5), or `sudo dnf install python3-wheel`, then I no longer have this issue.

Not sure why I hadn't installed that long ago? Maybe because `venv`, `virtualenv`, and `poetry` do it automatically?

**Comment by David-OConnor** [comment]
I (oops) can't remember, but I think Wheel's expected to be included with Python... Ie it is in the Windows installer, and is in the one Pyflow installs on Windows as-of a few weeks ago. It isn't on the one pyflow installs on Linux, and is usually on system Linuxes but may not be.

Pyflow's supposed to check and try to install it anyway on Linux/Mac, but evidently that's not working properly.

**Comment by David-OConnor** [comment]
Fixed, I believe.
