### ISSUE TITLE
Installation on macos fails

### ISSUE THREAD

**Issue by MxFlix** [David-OConnor/pyflow#76]
I'm hoping to use pyflow to distribute an app I'm developing, so I'm also using it to run the tests on TravisCI. However, the MacOS test is proving to be tricky, as the installation of pyflow via Rust fails with this error.:
```
error[E0308]: mismatched types
   --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/pyflow-0.2.7/src/install.rs:405:29
    |
405 |                 util::abort(error);
    |                             ^^^^^
    |                             |
    |                             expected `&str`, found struct `std::string::String`
    |                             help: consider borrowing here: `&error`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
error: failed to compile `pyflow v0.2.7`, intermediate artifacts can be found at `/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/cargo-installNfr0yT`

```
Additionally, the mac binary linked in the readme only returns "not found" :(

**Comment by David-OConnor** [comment]
Oops - broken README link. The one that exists is a few versions out of date though. That test is broken due to a typo in the last release. I fixed it in the repo and binaries immediately after, but the version on Crates.io is broken, as you pointed out.

You could try cloning the repo, and installing it that way.

**Comment by MxFlix** [comment]
I have unfortunately absolutely no clue about Rust (or Macs, for that matter). How do I build it locally? Do I cd into the cloned repo and use "cargo install"? And will it then be installed globally?

**Comment by David-OConnor** [comment]
You'd (assuming Rust is installed) cd into the repo and use `cargo build --release`. It will produce a standalone executable in `target/release`. Place this somewhere accessible by the Path.

This isn't ideal, but is the only way I can think of to get this running on Mac before another release, and/or someone builds a mac binary.

**Comment by David-OConnor** [comment]
@MxFlix : Btw, if you do get that working, could you email me the binary? Would love to host it on the binary repo associated with this, so others on Mac can just DL the binary.

**Comment by MxFlix** [comment]
@David-OConnor I did get it to work (almost - I hadn't seen that installing python on MacOS isn't supported, which is exactly what I had wanted to test), but unfortunately, I don't know at all how I would get the resulting binary from the Travis server onto my computer, so I can't send it to you. Sorry! :(

**Comment by David-OConnor** [comment]
Btw - the reason for installing Python on MacOs not working is the same - Not owning a Mac, I have no way of building standalone Python binaries for it.

**Comment by ryuta69** [comment]
@David-OConnor 
Hi, thank you for great OSS.
I'm playing around, and found this issue.

Shall I send you binary built by MacOS(latest Catalina)?

**Comment by David-OConnor** [comment]
That'd be much appreciated!

**Comment by ryuta69** [comment]
@David-OConnor 
Hi, I couldn't send email via gmail because of security alert, I published the binary here.

https://github.com/ryuta69/pyflow/releases/tag/9.99

**Comment by David-OConnor** [comment]
Thank you! Uploaded.

**Comment by David-OConnor** [comment]
Fixed via Brew
