### ISSUE TITLE
Panic installing units

### ISSUE THREAD

**Issue by tpoliaw** [David-OConnor/pyflow#77]
Installing units causes a panic. Installing 'normally' via pip works as expected.

pyflow built from current master (510ff54629e), Python 3.8.2.

    /tmp/demo master✻
    ❯ RUST_BACKTRACE=1 pyflow install units
    thread 'main' panicked at 'Unable to find a release for units = "0.7.0"', src/dep_resolution.rs:118:28
    stack backtrace:
       0: backtrace::backtrace::libunwind::trace
                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
       1: backtrace::backtrace::trace_unsynchronized
                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
       2: std::sys_common::backtrace::_print_fmt
                 at src/libstd/sys_common/backtrace.rs:78
       3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
                 at src/libstd/sys_common/backtrace.rs:59
       4: core::fmt::write
                 at src/libcore/fmt/mod.rs:1069
       5: std::io::Write::write_fmt
                 at src/libstd/io/mod.rs:1504
       6: std::sys_common::backtrace::_print
                 at src/libstd/sys_common/backtrace.rs:62
       7: std::sys_common::backtrace::print
                 at src/libstd/sys_common/backtrace.rs:49
       8: std::panicking::default_hook::{{closure}}
                 at src/libstd/panicking.rs:198
       9: std::panicking::default_hook
                 at src/libstd/panicking.rs:218
      10: std::panicking::rust_panic_with_hook
                 at src/libstd/panicking.rs:511
      11: rust_begin_unwind
                 at src/libstd/panicking.rs:419
      12: std::panicking::begin_panic_fmt
                 at src/libstd/panicking.rs:373
      13: pyflow::dep_resolution::get_warehouse_release::{{closure}}
      14: pyflow::dep_resolution::get_warehouse_release
      15: pyflow::sync
      16: pyflow::main
      17: std::rt::lang_start::{{closure}}
      18: std::rt::lang_start_internal::{{closure}}
                 at src/libstd/rt.rs:52
      19: std::panicking::try::do_call
                 at src/libstd/panicking.rs:331
      20: std::panicking::try
                 at src/libstd/panicking.rs:274
      21: std::panic::catch_unwind
                 at src/libstd/panic.rs:394
      22: std::rt::lang_start_internal
                 at src/libstd/rt.rs:51
      23: main
      24: __libc_start_main
      25: _start
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by David-OConnor** [comment]
This is likely triggered by Units using a 2-part version info. Should be a quick fix in the version parse code.

**Comment by David-OConnor** [comment]
Ok, it's actually caused by the leading 0 in the version, eg `0.07`.
