### ISSUE TITLE
"this is likely a bug in the cacheing process" - Error message could be shorter

### ISSUE THREAD

**Issue by MxFlix** [David-OConnor/pyflow#79]
This isn't a bug at all, just a suggestion:
When a new package is installed, it happens from time to time that the dependencies need to be newly cached, which can take a little while. This then results in a *very* long error message, which contains the entire requirements list in formatted JSON. Through that, the actual important information, "Problem getting dependency data - this is likely a bug in the cacheing process. Please try again in a few minutes." is hidden, even on bigger screens (depending on the amount of packages, of course).

Additionally, the message is completely in deep red, making it seem like something went horribly wrong, when it actually *kinda* didn't.

I would suggest putting the informative message at the bottom of the JSON (if that is even needed at all) and displaying it in the default color. Or maybe even rewording it along the lines of "It's taking a long time to get dependency data - this usually suggests that the dependency tree is being newly built. Please try again in a few minutes, and if the error still occurs, consider opening an issue on github."

I would try my hands at a pull request, but I have no idea where the string in question is defined, and also have absolutely no idea how this whole PR thing works^^"

**Comment by MxFlix** [comment]
I have since discovered that I got that error message quite often because there was (or rather, still is) something wrong with my home network's DNS settings, as I get a NXDOMAIN error on herokuapps.com (and only there) whenever something in the network doesn't feel like it. (I will get to the bottom of that, but it is not a pyflow issue in any way.)

Though as manually calling a "new" packages pydeps page (from a non-wonky network) still gives an "Application Error" (just a nicely formatted one from Heroku), which presumably results in the same console output as described above, my point still stands. I think. YMMV, of course :)

**Comment by David-OConnor** [comment]
I agree on the error message corrections you mention, even if it was triggered a network error. 

Another thing that triggers this: In order to avoid speed and other problems other package managers have (caused by the python package repo not providing reliable dependency info), that heroku repo you mention is a cache that stores dependency info. The first time a package/version is asked for, it may trigger this error, then go away in a few mins once it's done caching.

**Comment by ElijahSink** [comment]
I've taken a stab at this. Let me know if I should tweak something.
