### ISSUE TITLE
VSCode .venv detection

### ISSUE THREAD

**Issue by danielloader** [David-OConnor/pyflow#8]
I'm not sure if this is strictly your problem per se, and I'm unsure if it'd get fixed by waiting and allowing the PEP-582 solution going into python 3.8 and thus hoping VSCode picks it up for detection, but it may be worth posting akin to the poetry project:

https://github.com/microsoft/vscode-python/issues/1871

I don't know the details of the PEP enough to know if your implementation is "standards compliant" enough that this will eventually filter down anyway.

Food for thought - I expect they'll want a larger userbase and a more mature project before supporting it specially though.

As an aside I'm left in a bit of a pickle now as to what to set the python interpreter too on VSCode to do linting/formatting.

**Comment by David-OConnor** [comment]
This is one of the biggest open questions, in that it significantly hurts the workflow. It's a problem with PyCharm too, and I'm not sure how to fix it. Maybe writing plugins for popular IDEs like those two?

**Comment by David-OConnor** [comment]
I think I've found a solution:


- In VsCode, select `File`, `Add Folder to Workspace...`, and select
`__pypackages__/3.x/lib`.

- In PyCharm, using the tree on the left, right click `__pypackages__/3.x/lib`,
select `Mark directory as`, `Sources Root`.

**Comment by danielloader** [comment]
Thanks for looking at this, annoying it also breaks the vscode python debugger - so as it stands not sure how to go about using this environment with vscode properly.

Appreciate the effort though!

**Comment by David-OConnor** [comment]
`Settings` → search `python extra paths` →
 `Edit in settings.json` → Add the line: 
 `"python.autoComplete.extraPaths": ["(projname)/__pypackages__/3.7/lib"]`

Will be in README in next commit
