### ISSUE TITLE
Refactoring of code for parsing dependencies

### ISSUE THREAD

**Issue by higumachan** [David-OConnor/pyflow#83]
Hi.

When I looked at the code in dep_types.rs, I thought the code was a bit hard to read with many regular expressions.([example](https://github.com/David-OConnor/pyflow/blob/master/src/dep_types.rs#L205-L242))
In my opinion, refactoring using [nom](https://github.com/Geal/nom) will make the code more readable.

If you are in favor of this idea, then I would like to put out a PR that performs this refactoring. (I can also show you some examples of rewriting with nom before the overall decision)

Thanks.

**Comment by David-OConnor** [comment]
I agree. That section of the code is a mess. (As is the main entry point). I'll merge the PR.
