### ISSUE TITLE
ModuleNotFoundError: No module named 'pyflow'

### ISSUE THREAD

**Issue by Malithi-gif** [David-OConnor/pyflow#93]
The same error gives when pyflow installed.

**Comment by David-OConnor** [comment]
What installation method did you use, and on what Os?

**Comment by Malithi-gif** [comment]
Windows

**Comment by David-OConnor** [comment]
Could you please post your pyproject.toml? Thank you.

**Comment by arezkibouzid** [comment]
any solution ?

**Comment by David-OConnor** [comment]
Could you please post your pyproject.toml?

**Comment by arezkibouzid** [comment]
> Could you please post your pyproject.toml?

thnx for reply but i resolved it
