### ISSUE TITLE
Debian 10 was misrecognized as "manylinux2014_ppc64le"

### ISSUE THREAD

**Issue by quycao** [David-OConnor/pyflow#94]
- OS: Linux debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
- Shell: bash
- Python: not installed
- pyflow: pyflow 0.2.9
- CPU: Intel x86 64bit

Error message:
`
$ pyflow install matplotlib  
Found lockfile  
⬇ Installing pyparsing 2.4.7 ...  
⬇ Installing numpy 1.19.4 ...  
Added a console script: f2py  
Added a console script: f2py3  
Added a console script: f2py3.8  
⬇ Installing six 1.15.0 ...  
⬇ Installing matplotlib 3.3.3 ...  
⬇ Installing pillow 8.0.1 ...  
thread 'main' panicked at 'Problem parsing Os: manylinux2014_ppc64le',   src/util.rs:643:53  
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace  
`

**Comment by David-OConnor** [comment]
Thanks. Bug.

**Comment by David-OConnor** [comment]
I bandaid-fixed it. For the fix, clone the repo, install rust, and run `cargo build --release`. Then run the resulting binary in the `target` directory to use.

**Comment by quycao** [comment]
Thank you, I built it from your updated code and it work :)

**Comment by David-OConnor** [comment]
Sweet!
