### ISSUE TITLE
`pyflow script` crashes upon encountering an empty `__requires__`

### ISSUE THREAD

**Issue by mataha** [David-OConnor/pyflow#96]
I have a project with a few sidecar scripts looking roughly like this:

```python3
#!/usr/bin/env python3

__requires__ = []
__version__ = "0.0.1"
__author__ = "mataha"

# body...
```

Most of the time `__requires__` contains some dependencies - here, it was included for consistency.
Assuming this script is named `simple.py` - when ran with `pyflow script simple.py`, `pyflow` crashes:

```
thread 'main' panicked at 'Problem getting version info for ', K:\.cargo\registry\src\github.com-1ecc6299db9ec823\pyflow-0.2.9\src\main.rs:1024:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mataha** [comment]
Looking at the code, multiline `__requires__` should suffer from a similar issue, and it does:

```python3
__requires__ = ["beautifulsoup4",
                ...
                "requests"]
```

When ran with `pyflow script simple.py`:

```
Traceback (most recent call last):
  File "K:\simple.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
(Though maybe that should be in a separate issue.)

**Comment by David-OConnor** [comment]
Fixed with your PR
