### ISSUE TITLE
`pyflow script` Windows error: thread 'main' panicked

### ISSUE THREAD

**Issue by everetr** [David-OConnor/pyflow#98]
Windows 10. pyflow 0.2.9 installed via Scoop. I enter this in PowerShell and choose Python 3.8:

```powershell
pyflow script C:/Users/<me>/Documents/test/test.py
```

Error:

```
thread 'main' panicked at 'Problem creating a file to store the Python version for this script: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\main.rs:980:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`test.py`:

```python3
print("Hi")
```

Same thing happens if `test.py` looks like this:

```python3
__requires__ = ["pandas", "requests"]

import pandas as pd
import requests

print("Hi")
```

Same thing happens with either script if I choose any Python 3.*. This error does *not* occur on Manjaro Linux.

**Comment by tanj** [comment]
@David-OConnor I added some extra debug info to the `fs::File::create` call that throws this error. It appears as though if you try and run a script that is not part of a project on windows `py_vers_path` ends up looking like `C:\dev\python\junk\pyflow_98_test.py\py_vers.txt`

I'm thinking the easiest way to fix this (without more digging) is to check if the path `env_path` exists and if it is a directory. If it exists and is a file then we prefix the file name with a `.` and create that directory.

I'll do some further looking to see why `script_env_path` is not something else like `%APPDATA%\pyflow\script-envs`

Let me know what you think.

**Comment by tanj** [comment]
Digging further it appears to be an issue if you use an absolute path. This affects both windows and linux if the script file name is given as an absolute path. Relative paths seem to be fine on both OS's.

[`let env_path = script_env_path.join(&filename)`](https://github.com/David-OConnor/pyflow/blob/cc31adec3b4147352872c34bb37a04881221a86b/src/main.rs#L963) is the offending line.
